Add support for numpy version 2.x
Also make sure that we run all python tests with both numpy version 1.x
and version 2.x on CI.

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -134,16 +134,53 @@ jobs:
       - name: Build Python package
         run: poetry run maturin develop --release --features pybindings
 
-      - name: pytest
+      - name: pytest with numpy version 1.26
         shell: bash
         run: |
-          poetry run pytest tests/python | tee pytest.out
+          poetry run python -m pip install numpy~=1.26
+          INSTALLED_NUMPY_VERSION=$(poetry run python -c 'import numpy; print(numpy.__version__)')
+          echo "Installed numpy version: $INSTALLED_NUMPY_VERSION"
+          if [ "x${INSTALLED_NUMPY_VERSION:0:5}y" == "x1.26.y" ]; then
+            echo "Numpy version matches expectation."
+          else
+            echo "ERROR: wrong numpy version."
+            exit 1
+          fi
+          poetry run pytest tests/python | tee pytest-numpy1.out
           exit ${PIPESTATUS[0]}
 
       - name: Verify that pytest used correct python version
         shell: bash
         run: |
-          USED_PYTHON_VERSION=$(grep -A1 -iE '^=+ test session starts =+$' pytest.out | perl -ne 'if ($_ =~ / -- Python (\d+\.\d+)\.\d+/i) { print "$1"; }')
+          USED_PYTHON_VERSION=$(grep -A1 -iE '^=+ test session starts =+$' pytest-numpy1.out | perl -ne 'if ($_ =~ / -- Python (\d+\.\d+)\.\d+/i) { print "$1"; }')
+          echo "Expected python version: ${{ matrix.python-version }}"
+          echo "Found python version:    $USED_PYTHON_VERSION"
+          if [ "x${{ matrix.python-version }}y" == "x${USED_PYTHON_VERSION}y" ]; then
+            echo "Versions match."
+          else
+            echo "ERROR: versions don't match."
+            exit 1
+          fi
+
+      - name: pytest with numpy version 2.x
+        shell: bash
+        run: |
+          poetry run python -m pip install numpy~=2.1
+          INSTALLED_NUMPY_VERSION=$(poetry run python -c 'import numpy; print(numpy.__version__)')
+          echo "Installed numpy version: $INSTALLED_NUMPY_VERSION"
+          if [ "x${INSTALLED_NUMPY_VERSION:0:2}y" == "x2.y" ]; then
+            echo "Numpy version matches expectation."
+          else
+            echo "ERROR: wrong numpy version."
+            exit 1
+          fi
+          poetry run pytest tests/python | tee pytest-numpy2.out
+          exit ${PIPESTATUS[0]}
+
+      - name: Verify that pytest used correct python version
+        shell: bash
+        run: |
+          USED_PYTHON_VERSION=$(grep -A1 -iE '^=+ test session starts =+$' pytest-numpy2.out | perl -ne 'if ($_ =~ / -- Python (\d+\.\d+)\.\d+/i) { print "$1"; }')
           echo "Expected python version: ${{ matrix.python-version }}"
           echo "Found python version:    $USED_PYTHON_VERSION"
           if [ "x${{ matrix.python-version }}y" == "x${USED_PYTHON_VERSION}y" ]; then
