Release workflow fails early if invalid metadata
This is a bit pedantic since it's already tested for in `test.yaml`, and
since twine will refuse to upload packages with invalid metadata anyway,
but it's cheap and avoids complications during release in case the last
run of `test.yaml` was a while back.

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -146,7 +146,17 @@ jobs:
         uses: dtolnay/rust-toolchain@stable
 
       - name: Build Python package
-        run: poetry run maturin develop --release --features pybindings
+        run: poetry run maturin build --release --features pybindings
+
+      - name: List wheel and verify metadata
+        shell: bash
+        run: |
+          ls -l target/wheels/
+          poetry run twine check target/wheels/*.whl
+
+      - name: Install Python package
+        shell: bash
+        run: poetry run pip install --force-reinstall target/wheels/*.whl
 
       - name: pytest with numpy version 1.x
         if: matrix.python-version != '3.13' && matrix.python-version != '3.14'
@@ -289,9 +299,9 @@ jobs:
       # we use `--skip-existing` in `twine upload` below.
       - name: Publish on crates.io
         if: github.event_name == 'release'
-        run: |
-          cargo login ${{ secrets.CARGO }}
-          cargo publish || echo "Publishing failed."
+        run: cargo publish || echo "Publishing failed."
+        env:
+          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO }}
 
   python-publish:
     needs: testall
@@ -391,19 +401,25 @@ jobs:
           command: build
           args: --release --strip --features pybindings -i python3.9 python3.10 python3.11 python3.12 python3.13 python3.14
 
-      - name: List wheels and verify metadata
-        shell: bash
-        run: |
-          ls -l target/wheels/
-          poetry run twine check target/wheels/*.whl
-
       - name: Save artifact with wheels for ${{ matrix.os }}
         uses: actions/upload-artifact@v4
         with:
           name: wheels-${{ matrix.os }}
           path: ./target/wheels/
 
-      - name: Test install wheels
+      - name: Install Python dependencies (for twine)
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install poetry
+          poetry install --no-root
+
+      - name: List wheels and verify metadata
+        shell: bash
+        run: |
+          ls -l target/wheels/
+          poetry run twine check target/wheels/*.whl
+
+      - name: Test install wheels (only one will work per OS)
         shell: bash
         run: |
           for i in target/wheels/*.whl; do
@@ -418,13 +434,7 @@ jobs:
             echo
           done
 
-      - name: Install Python dependencies (for twine)
-        run: |
-          python -m pip install --upgrade pip
-          python -m pip install poetry
-          poetry install --no-root
-
-      # We use `--skip-existing` here so that we can run The release script again
+      # We use `--skip-existing` here so that we can run the release script again
       # (possibly after fixing maturin issues) if it failed on just some files.
       - name: Publish wheels
         if: github.event_name == 'release'
